### PR TITLE
Improve responsive layout

### LINKED ISSUE #7: Improve responsive layout
# Text cutting issue & calendar icon size
screen shot 2016-07-10 at 15 17 52

# Layout error
screen shot 2016-07-10 at 15 20 31

### PR DESCRIPTION
**Pull request by adilsoncarvalho**
Fixing the responsive layout items requested on #7 

Resolves #7

### CODE REVIEW

**Comment by adilsoncarvalho** [comment]
# Text cutting

> it was

screen shot 2016-10-16 at 16 31 04

> it is now

screen shot 2016-10-16 at 16 32 10

**Comment by adilsoncarvalho** [comment]
# Event item calendar icon size

> it was

screen shot 2016-10-16 at 16 41 25

> it is now

screen shot 2016-10-16 at 16 41 49

---

I also took the chance and fixed the size for the desktop layout making both more proportional

> it was

screen shot 2016-10-16 at 16 43 53

> it is now

screen shot 2016-10-16 at 16 44 20

**Comment by adilsoncarvalho** [comment]
Hey @vyper, can you help me to figure it out what is the issue on the **Layout Error** on issue #7?

**Comment by vyper** [comment]
@adilsoncarvalho when I am logged as admin, menu break the line... Maybe add icon to open menu is a better way?

**Comment by adilsoncarvalho** [comment]
It seems this is ok now, @vyper 

:shipit: ?

**Comment by vyper** [comment]
Is broken @adilsoncarvalho 😬

Sign in (using http://localhost:3000) and in rails console use: `User.find_by(nickname: 'adilsoncarvalho').update admin: true`... So, you should see the error. (:

screen shot 2016-10-16 at 19 26 33

**Comment by adilsoncarvalho** [comment]
@vyper 😕 which is your resolution?

screen shot 2016-10-16 at 22 46 08

**Comment by vyper** [comment]
Only now I saw... `iPhone SE`, sorry for my confusion. It's still used? 😂

Is fine for me! :+1:

**Comment by adilsoncarvalho** [comment]
image

😂

**Pull request merged**
