### PR TITLE
Add config/database.yml.example

### PR DESCRIPTION
**Pull request by lccezinha**
When I try to run the project in my env, I had some problems with database configuration.

So a did this configuration to improve database setup without commit yours credentials directly inside `config/databse.yml`

### CODE REVIEW

**Comment by vyper** [comment]
@lccezinha For accept your pull request, we need resolve two things!

- Change `.travis.yml` to copy `config/database.yml.example` to `config/database.yml` for build on travis
- I don't know how to Heroku work without config/database.yml on repository. You know?

**Comment by Danielpk** [comment]
@vyper Heroku create database.yml at build process.

https://github.com/heroku/heroku-buildpack-ruby/blob/2e2a4971af6355ef12016c4ee95f321f357a424e/lib/language_pack/ruby.rb#L627

**Comment by vyper** [comment]
Cool @Danielpk! So... we need only fix `travis.yml`! (:

**Comment by lccezinha** [comment]
I will fix.

**Comment by vyper** [comment]
But... This branch is building correctly. Do we need to fix something? HEHE

**Comment by adilsoncarvalho** [comment]
As your build didn't failed I think Travis is ok. It probably overrides the `database.yml` as it only stands for connection parameters that are already handled by Travis. Maybe just keep things as they are.

**Comment by lccezinha** [comment]
I notice that, the build is fine.

Need to fix `.travis.yml` or not ?

**Comment by vyper** [comment]
Worked... fine!

**Comment by lccezinha** [comment]
Nice! :+1:

**Comment by vyper** [comment]
Thanks! (:

**Pull request merged**
