### PR TITLE
Force timezone value(occurred_at) in simple_form string input

### PR DESCRIPTION
**Pull request by fabiosammy**
Maybe can solve #11 (Success for me), but, how i can write test for it?

### CODE REVIEW

**Comment by lccezinha** [comment]
What do you think about write a instance method called `ocurred_at`, like this:

```ruby
def ocurred_at
  occurred_at.in_time_zone('Brasilia').strftime('%d-%m-%Y  %H:%M')
end
```

So I can just create a spec to validate this in models specs.

**Comment by vyper** [comment]
I don't like this approach. Many code hardcoded...  We like more flexible APP... (:

**Comment by vyper** [comment]
In last update of rails, bug is corrected!

**Comment by lccezinha** [comment]
WOW, nice!

**Pull request closed without merging**
