### PR TITLE
Profile improvements

### PR DESCRIPTION
**Pull request by brunoocasali**
Please merge https://github.com/guru-pr/gurupr/pull/229 first!

image
image

### CODE REVIEW

**Comment by vyper** [comment]
Thanks again @brunoocasali! Good #hacktoberfest for us! (;

**Comment by vyper** [comment]
Ouch! After deploy... broken site, because site does not run over https );

**Comment by brunoocasali** [comment]
@vyper I'll provide tests for that changes (i've forgotten when I created year ago) ;)

**Comment by brunoocasali** [comment]
> Ouch! After deploy... broken site, because site does not run over https );

Yeah, I spend some hours thinking about "Edit" click in profile not working, https (sabayon + cps (mainly cps)) makes me crazy!

**Pull request merged**
