### PR TITLE
Create seed data to help local development

### PR DESCRIPTION
**Pull request by neves**
rake db:seed and you are ready to try locally with "real" data.
This seed creates 1 admin user, 1 normal user and 1 event in the future.

### CODE REVIEW

**Comment by adbatista** [comment]
why not use FactoryGirl to seed data?

**Comment by neves** [comment]
I was thinking about that for a next step.

**Comment by vyper** [comment]
@neves How can the user `sign in`? `uid` and `email` is invalid to github oauth.

Maybe we should just keep only seeds for events and we should improve instructions for create a admin user.

**Comment by neves** [comment]
Sorry @vyper, but does /join works on local? I tried here and got github 404 page, with url:
https://github.com/login/oauth/authorize?client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=user%3Aemail&state=d404b9b10a44676e6515371d9e4ba32d76361f7fb8958a10

**Comment by vyper** [comment]
Yes @neves, work on local. 

Keys on [env.sample](https://github.com/guru-pr/gurupr/blob/master/.env.example) work with `localhost:3000`.

**Comment by neves** [comment]
I updated it to just create 2 normal users, as I can login myself with my own github account.

**Pull request merged**
